POST localhost:8082/users
Content-Type: application/json

{
  "name": "Artur1",
  "surname": "Vahanyan1",
  "email": "artur.vaganyan96@gmail.com1",
  "password": "a1",
  "role": "ADMIN"
}

###

PUT localhost:8082/login
Content-Type: application/json

{
  "username": "artur.vaganyan96@gmail.com1",
  "password": "a1"
}

###

GET localhost:8082/users/current-user
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhcnR1ci52YWdhbnlhbjk2QGdtYWlsLmNvbTEiLCJBdXRob3JpdGllcyI6WyJBRE1JTiJdLCJpZCI6MiwiZXhwIjoxNTg4Nzg4ODAyfQ.aqBkxLRi02_Iie-UbwY9Dk6GB68Kkek7Ej6dL_hn3qpwhZvABUb1PVdYHi0Sco1p081SEaa1wZfcn8kN1kHwVA