### GET products
GET localhost:8082/api/products?name=Red
Authorization:  Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhcnR1ci52YWdhbnlhbjk2QGdtYWlsLmNvbSIsIkF1dGhvcml0aWVzIjpbIkFETUlOIl0sImlkIjoxLCJleHAiOjE1OTAzNDQ3MjV9.zzluA1GR9b0llli4EUz4ArVX4TFHsvnErazq5pqqEmNEAh5Pt7eiWWjWaGlaMrC4b1XM2nxKprwRkECzqTL6Iw
