### GET products
GET localhost:8082/api/products?name=Red
Authorization:  Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhcnR1ci52YWdhbnlhbjk2QGdtYWlsLmNvbSIsIkF1dGhvcml0aWVzIjpbIkNVU1RPTUVSIl0sImlkIjoxLCJleHAiOjE1OTA5NTMwMzR9.qBWuTcasl5SKhtBTaRk497fEFvX7H4M-GGX48WNoJBt6m4DVJpaCdDrXvTVopPJ6vUrERgR9pWg65VdFZFVH6Q
